const TZ='America/Indiana/Indianapolis',DAY=86400000;
const API={progress:'/api/task-progress',academics:'/api/dashboard?scope=academics',daily:'/api/dashboard?scope=daily',calendar:'/api/calendar-data'};
const WEATHER='https://api.open-meteo.com/v1/forecast?latitude=40.4237&longitude=-86.9212&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code&hourly=temperature_2m,precipitation_probability,weather_code&daily=temperature_2m_max,temperature_2m_min&temperature_unit=fahrenheit&timezone=America%2FIndiana%2FIndianapolis&forecast_days=2';
const NOTION='https://www.notion.so/3d577f3edfc681aeb496d00903ddb4a7';
const SEM_START='2026-08-24',SEM_END='2026-12-20',FALL_BREAK='2026-10-12',COLLEGE_START='2026-08-24',COLLEGE_END='2030-05-12';
const HABITS=['Meditate','Journal','Sleep early','Pray','Chinese'],ATH=['Stretch','Swim','Rehab','Cardio'],WORKOUT_PLAN=['Push','Pull','Legs','Rest','Push','Pull','Legs'];
const WMO={0:['☀️','Clear'],1:['🌤️','Mostly clear'],2:['⛅','Partly cloudy'],3:['☁️','Cloudy'],45:['🌫️','Fog'],48:['🌫️','Fog'],51:['🌦️','Light drizzle'],53:['🌦️','Drizzle'],55:['🌧️','Heavy drizzle'],61:['🌦️','Light rain'],63:['🌧️','Rain'],65:['🌧️','Heavy rain'],66:['🌧️','Freezing rain'],67:['🌧️','Freezing rain'],71:['🌨️','Light snow'],73:['🌨️','Snow'],75:['❄️','Heavy snow'],77:['❄️','Snow grains'],80:['🌦️','Rain showers'],81:['🌧️','Rain showers'],82:['⛈️','Heavy showers'],85:['🌨️','Snow showers'],86:['🌨️','Heavy snow showers'],95:['⛈️','Thunderstorms'],96:['⛈️','Storms + hail'],99:['⛈️','Storms + hail']};
const state={progress:null,academics:{assignments:{},events:{}},daily:{days:{}},calendar:{assignments:[],events:[]},weather:null,month:null,calendarFilter:'both',selectedDate:null};
const $=id=>document.getElementById(id);
function tzParts(now=new Date()){return Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,hourCycle:'h23'}).formatToParts(now).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]))}
function localMs(now=new Date()){const p=tzParts(now);return Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)}
function todayKey(){const p=tzParts();return `${p.year}-${p.month}-${p.day}`}
function dateMs(s){if(!s)return 0;const[y,m,d]=s.slice(0,10).split('-').map(Number);return Date.UTC(y,m-1,d)}
function key(ms){return new Date(ms).toISOString().slice(0,10)}
function monday(ms){const dow=new Date(ms).getUTCDay();return ms-((dow+6)%7)*DAY}
function clamp(v,a=0,b=1){return Math.max(a,Math.min(b,v))}
function pct(now,start,end){return clamp((now-start)/(end-start))*100}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function human(ms){if(ms<=0)return'now';const mins=Math.floor(ms/60000);if(mins<60)return `${mins}m`;const h=Math.floor(mins/60);if(h<24)return `${h}h ${mins%60}m`;const d=Math.floor(h/24);return `${d}d ${h%24}h`}
function eventTime(v){if(!v)return 0;if(v.length===10)return dateMs(v)+12*3600000;const n=new Date(v).getTime();return Number.isFinite(n)?n:0}
function eventDay(v){if(!v)return'';if(v.length===10)return v;return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v))}
function fmtDateTime(v){const ms=typeof v==='number'?v:eventTime(v);if(!ms)return'';return new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(ms))}
function fmtShortDay(k){return new Intl.DateTimeFormat('en-US',{timeZone:'UTC',month:'short',day:'numeric'}).format(new Date(dateMs(k)))}
function updateClock(){const n=new Date();$('clock').textContent=new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'numeric',minute:'2-digit',second:'2-digit'}).format(n);$('dateLine').textContent=new Intl.DateTimeFormat('en-US',{timeZone:TZ,weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(n)}
function setProgress(id,value,meta){const el=$(id+'Fill'),m=$(id+'Meta');if(el)el.style.width=`${Math.max(0,Math.min(100,value)).toFixed(1)}%`;if(m)m.textContent=meta}
function renderHeroProgress(){const now=localMs();const b=pct(now,dateMs(SEM_START),dateMs(FALL_BREAK)),s=pct(now,dateMs(SEM_START),dateMs(SEM_END)),c=pct(now,dateMs(COLLEGE_START),dateMs(COLLEGE_END));setProgress('break',b,now<dateMs(FALL_BREAK)?`${human(dateMs(FALL_BREAK)-now)} · ${b.toFixed(1)}%`:'reached · 100%');setProgress('sem',s,`${s.toFixed(1)}%`);setProgress('college',c,`${c.toFixed(1)}%`)}
function renderWeather(){const w=state.weather;if(!w)return;const c=w.current||{},d=w.daily||{},desc=WMO[c.weather_code]||['🌊','Current conditions'];$('weatherIcon').textContent=desc[0];$('weatherTemp').textContent=`${Math.round(c.temperature_2m)}°`;$('weatherCond').textContent=desc[1];$('feels').textContent=`${Math.round(c.apparent_temperature)}°`;$('hilo').textContent=`${Math.round(d.temperature_2m_max?.[0])}° / ${Math.round(d.temperature_2m_min?.[0])}°`;$('humidity').textContent=`${Math.round(c.relative_humidity_2m)}%`;const times=w.hourly?.time||[],temps=w.hourly?.temperature_2m||[],rain=w.hourly?.precipitation_probability||[],codes=w.hourly?.weather_code||[];const p=tzParts();const hk=`${p.year}-${p.month}-${p.day}T${p.hour}:00`;let idx=times.findIndex(t=>t>=hk);if(idx<0)idx=0;const hours=[];for(let i=idx;i<Math.min(idx+6,times.length);i++)hours.push({time:times[i],temp:temps[i],rain:rain[i]??0,code:codes[i]});$('rainMax').textContent=`${Math.round(Math.max(0,...hours.map(x=>x.rain)))}%`;$('forecast').innerHTML=hours.map(x=>{const icon=(WMO[x.code]||['🌊'])[0],h=+x.time.slice(11,13),label=(h%12||12)+(h>=12?'p':'a'),r=Math.round(x.rain||0);return `<div class="hour"><div class="hour-time">${label}</div><div class="hour-icon">${icon}</div><div class="hour-temp">${Math.round(x.temp)}°</div><div class="hour-rain">💧 ${r}%</div><div class="mini-rain"><i style="width:${r}%"></i></div></div>`}).join('')}
function calendarEventsFlat(){return state.calendar.events||[]}
function renderNext(){const now=Date.now();const all=calendarEventsFlat().filter(e=>eventTime(e.at)>now);const events=all.filter(e=>e.type!=='Class'&&e.type!=='Exam').sort((a,b)=>eventTime(a.at)-eventTime(b.at)).slice(0,2);const exams=all.filter(e=>e.type==='Exam').sort((a,b)=>eventTime(a.at)-eventTime(b.at)).slice(0,2);const row=(e)=>`<div class="next-item"><div class="next-name" title="${esc(e.name)}">${esc(e.name)}</div><div class="next-meta">${esc(e.course||e.type||e.category||'Event')} · ${esc(fmtDateTime(e.at))}</div><div class="next-count">in ${human(eventTime(e.at)-now)}</div></div>`;$('nextEvents').innerHTML=events.length?events.map(row).join(''):'<div class="empty">Nothing scheduled</div>';$('nextExams').innerHTML=exams.length?exams.map(row).join(''):'<div class="empty">No upcoming exams</div>'}
function renderTaskProgress(){const p=state.progress;if(!p)return;const t=p.today||{done:0,total:0,pct:0};$('todayRing').style.setProperty('--p',t.pct||0);$('todayPct').textContent=`${Math.round(t.pct||0)}%`;$('todayCount').textContent=`${t.done} / ${t.total} done`;for(const [id,k] of [['weekStat','week'],['allStat','all']]){const x=p[k]||{done:0,total:0,pct:0};$(id+'Fill').style.width=`${x.pct||0}%`;$(id+'Value').textContent=`${x.done} / ${x.total} · ${x.pct||0}%`}}
function renderDeadlineRadar(){const now=Date.now(),future=(state.calendar.assignments||[]).filter(a=>a.at&&eventTime(a.at)>=now-6*3600000).sort((a,b)=>eventTime(a.at)-eventTime(b.at)).slice(0,6);$('deadlineRadar').innerHTML=future.length?future.map(a=>{const d=new Date(eventTime(a.at));const day=new Intl.DateTimeFormat('en-US',{timeZone:TZ,day:'numeric'}).format(d),mon=new Intl.DateTimeFormat('en-US',{timeZone:TZ,month:'short'}).format(d);return `<a class="deadline" href="${esc(a.notion_url||NOTION)}" target="_blank" rel="noopener"><div class="deadline-date"><strong>${day}</strong>${mon}</div><div><div class="deadline-name">${esc(a.name)}</div><div class="deadline-meta">${esc(a.course||a.type||'Task')} · ${esc(fmtDateTime(a.at))}</div></div></a>`}).join(''):'<div class="empty">No upcoming deadlines</div>'}
function heatLevel(n,max=5){return Math.max(0,Math.min(max,n))}
function assignmentWeight(a){const t=(a.type||'').toLowerCase();if(t.includes('exam'))return 5;if(t.includes('project'))return 4;if(t.includes('lab'))return 3;if(t.includes('quiz')||t.includes('cfu'))return 2;return 1}
function eventWeight(e){const m={Exam:5,Practical:4,Roundtable:4,Presentation:3,Demonstration:3,Quiz:2,CFU:2,Meetup:1,Other:1};return m[e.type]||0}
function renderHeatmap(rootId,kind){const root=$(rootId),start=dateMs(SEM_START),end=dateMs('2026-12-19'),gs=monday(start),today=dateMs(todayKey()),cells=[];for(let w=0;w<17;w++)for(let d=0;d<7;d++){const ms=gs+(w*7+d)*DAY,k=key(ms);let items=[],lv=0;if(kind==='assign'){items=state.academics.assignments?.[k]||[];lv=items.length?Math.min(5,Math.max(...items.map(assignmentWeight))+items.length-1):0}else if(kind==='event'){items=(state.academics.events?.[k]||[]).filter(e=>e.type!=='Class'&&e.type!=='Break');lv=items.length?Math.min(5,Math.max(...items.map(eventWeight))+items.length-1):0}else if(kind==='habit'){const h=state.daily.days?.[k]?.habits||{};lv=HABITS.filter(x=>h[x]).length;lv=lv>=5?4:lv>=4?3:lv>=3?2:lv>=1?1:0}else if(kind==='productivity'){const p=state.daily.days?.[k]?.productivity||'';lv=p==='Yellow'?1:p==='Green'?2:p==='Purple'?3:0}let cls='heat-cell';if(ms<start||ms>end)cls+=' outside';if(ms>today&&(kind==='habit'||kind==='productivity'))cls+=' future';if(ms===today)cls+=' today';if(kind==='assign'&&lv)cls+=` assign-l${lv}`;if(kind==='event'&&lv)cls+=` event-l${lv}`;if(kind==='habit'&&lv)cls+=` habit-l${lv}`;if(kind==='productivity'){if(lv===1)cls+=' habit-l1';if(lv===2)cls+=' habit-l2';if(lv===3)cls+=' habit-l4'}const title=kind==='productivity'?`${k} · ${state.daily.days?.[k]?.productivity||'unrated'}`:`${k} · ${items.length||lv} ${kind}`;cells.push(`<div class="${cls}" title="${esc(title)}"></div>`)}root.innerHTML=cells.join('')}
function renderAllHeatmaps(){renderHeatmap('assignmentHeat','assign');renderHeatmap('eventHeat','event');renderHeatmap('habitHeat','habit');renderHeatmap('productivityHeat','productivity')}
function weekKeys(){const m=monday(dateMs(todayKey()));return Array.from({length:7},(_,i)=>key(m+i*DAY))}
async function writeDaily(day,changes){const local=state.daily.days||(state.daily.days={});local[day]=local[day]||{habits:{},athletics:{},workout:{}};for(const [k,v] of Object.entries(changes)){if(HABITS.includes(k))local[day].habits[k]=v;else if(ATH.includes(k))local[day].athletics[k]=v;else if(k==='Productivity')local[day].productivity=v;else if(k==='Workout Quality')local[day].workout.quality=v;else if(k==='Workout Type')local[day].workout.type=v}renderDailyPanels();setSave('saving…');try{const r=await fetch('/api/dashboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:day,changes})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const x=await r.json();state.daily=x;renderDailyPanels();setSave('saved to Notion')}catch(e){console.error(e);setSave('save failed')}}
function setSave(s){document.querySelectorAll('.save-state').forEach(x=>x.textContent=s)}
function renderHabits(){const keys=weekKeys(),days=['M','T','W','T','F','S','S'];let html='<div class="matrix"><div></div>'+days.map(x=>`<div class="headcell">${x}</div>`).join('');for(const h of HABITS){html+=`<div class="rowname">${h}</div>`;for(const k of keys){const on=!!state.daily.days?.[k]?.habits?.[h];html+=`<button class="cell-btn ${on?'on':''}" data-habit="${esc(h)}" data-day="${k}" title="${k} · ${h}">${on?'✓':''}</button>`}}html+='</div>';$('habitMatrix').innerHTML=html;$('habitMatrix').querySelectorAll('[data-habit]').forEach(b=>b.onclick=()=>writeDaily(b.dataset.day,{[b.dataset.habit]:!b.classList.contains('on')}));renderHeatmap('habitHeat','habit')}
function prodCycle(v){return v==='Yellow'?'Green':v==='Green'?'Purple':v==='Purple'?'':'Yellow'}
function renderProductivity(){const keys=weekKeys(),days=['M','T','W','T','F','S','S'];let html='<div class="matrix"><div class="rowname">Productivity</div>'+keys.map((k,i)=>{const v=state.daily.days?.[k]?.productivity||'';return `<button class="prod-cell ${v.toLowerCase()}" data-day="${k}" data-val="${esc(v)}" title="${days[i]} ${k} · ${v||'unrated'}"></button>`}).join('')+'</div>';$('productivityWeek').innerHTML=html;$('productivityWeek').querySelectorAll('.prod-cell').forEach(b=>b.onclick=()=>writeDaily(b.dataset.day,{Productivity:prodCycle(b.dataset.val)}));renderHeatmap('productivityHeat','productivity')}
function qualityClass(q){return q==='Not great'?'yellow':q==='Productive'?'green':q==='Great'?'purple':''}
function qualityCycle(q){return q==='Not great'?'Productive':q==='Productive'?'Great':q==='Great'?'':'Not great'}
function renderTraining(){const keys=weekKeys(),days=['M','T','W','T','F','S','S'];let sessions=0,sets=0,volume=0,latest='—',latestSub='no session';let html='<div class="matrix"><div class="rowname">Workout</div>'+keys.map((k,i)=>{const row=state.daily.days?.[k]||{},w=row.workout||{},plan=WORKOUT_PLAN[i],done=!!w.done||!!w.quality;if(plan!=='Rest'&&done)sessions++;sets+=Number(w.working_sets)||0;volume+=Number(w.volume)||0;if(done){latest=w.type||plan;latestSub=`${days[i]} · ${w.quality||'logged'}`}if(plan==='Rest')return `<button class="workout-cell rest" disabled>R</button>`;return `<button class="workout-cell ${qualityClass(w.quality)}" data-workout-day="${k}" data-quality="${esc(w.quality||'')}" data-type="${esc(w.type||plan)}" title="${k} · ${w.type||plan} · ${w.quality||'click to rate'}">${(w.type||plan).slice(0,1)}</button>`}).join('')+'</div>';for(const name of ATH){html+=`<div class="matrix" style="margin-top:6px"><div class="rowname">${name}</div>`+keys.map(k=>{const on=!!state.daily.days?.[k]?.athletics?.[name];return `<button class="cell-btn ${on?'on':''}" data-ath="${name}" data-day="${k}">${on?'✓':''}</button>`}).join('')+'</div>'}$('trainingMatrix').innerHTML=html;$('trainingMatrix').querySelectorAll('[data-workout-day]').forEach(b=>b.onclick=()=>writeDaily(b.dataset.workoutDay,{'Workout Quality':qualityCycle(b.dataset.quality),'Workout Type':b.dataset.type}));$('trainingMatrix').querySelectorAll('[data-ath]').forEach(b=>b.onclick=()=>writeDaily(b.dataset.day,{[b.dataset.ath]:!b.classList.contains('on')}));$('trainSessions').textContent=`${sessions} / 6`;$('trainSets').textContent=Math.round(sets).toString();$('trainVolume').textContent=volume>=10000?`${(volume/1000).toFixed(1)}k lb`:`${Math.round(volume).toLocaleString()} lb`;$('trainLatest').textContent=latest;$('trainLatestSub').textContent=latestSub}
function renderDailyPanels(){renderHabits();renderProductivity();renderTraining();renderAllHeatmaps()}
function itemDays(item){const s=eventDay(item.at);if(!s)return[];let e=item.end?eventDay(item.end):s;if(!e)e=s;let a=dateMs(s),b=dateMs(e);if(b<a)b=a;const out=[];for(let x=a;x<=b&&out.length<40;x+=DAY)out.push(key(x));return out}
function calendarItemsForDay(k){let out=[];if(state.calendarFilter!=='events')for(const a of state.calendar.assignments||[])if(eventDay(a.at)===k)out.push({...a,kind:'assignment'});if(state.calendarFilter!=='assignments')for(const e of state.calendar.events||[])if(itemDays(e).includes(k))out.push({...e,kind:e.type==='Exam'?'exam':e.type==='Class'?'class':e.type==='Break'?'break':'event'});return out.sort((a,b)=>eventTime(a.at)-eventTime(b.at))}
function renderCalendar(){const now=tzParts(),base=state.month||{y:+now.year,m:+now.month-1};state.month=base;const first=Date.UTC(base.y,base.m,1),firstDow=(new Date(first).getUTCDay()+6)%7,start=first-firstDow*DAY;const title=new Intl.DateTimeFormat('en-US',{timeZone:'UTC',month:'long',year:'numeric'}).format(new Date(first));$('monthTitle').textContent=title;let html=['M','T','W','T','F','S','S'].map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<42;i++){const ms=start+i*DAY,k=key(ms),items=calendarItemsForDay(k),other=new Date(ms).getUTCMonth()!==base.m,today=k===todayKey();html+=`<div class="daybox ${other?'other':''} ${today?'today':''}" data-cal-day="${k}"><div class="daynum">${new Date(ms).getUTCDate()}</div>${items.slice(0,3).map(x=>`<div class="calitem ${x.kind}" title="${esc(x.name)}">${esc(x.name)}</div>`).join('')}${items.length>3?`<div class="calitem event">+${items.length-3} more</div>`:''}</div>`}$('calendarGrid').innerHTML=html;$('calendarGrid').querySelectorAll('[data-cal-day]').forEach(d=>d.onclick=()=>{state.selectedDate=d.dataset.calDay;renderCalendarDetails()});if(!state.selectedDate)state.selectedDate=todayKey();renderCalendarDetails()}
function renderCalendarDetails(){const k=state.selectedDate||todayKey(),items=calendarItemsForDay(k);$('detailsTitle').textContent=new Intl.DateTimeFormat('en-US',{timeZone:'UTC',weekday:'long',month:'long',day:'numeric'}).format(new Date(dateMs(k)));$('calendarDetailsList').innerHTML=items.length?items.map(x=>{const url=x.source||x.notion_url||NOTION;return `<div class="detail-row"><a href="${esc(url)}" target="_blank" rel="noopener">${esc(x.name)}</a><div class="detail-meta">${esc(x.course||x.type||x.category||x.kind)}${x.at&&x.at.length>10?' · '+esc(fmtDateTime(x.at)):''}</div></div>`}).join(''):'<div class="empty">Nothing scheduled</div>'}
function changeMonth(delta){let {y,m}=state.month||{y:+tzParts().year,m:+tzParts().month-1};m+=delta;if(m<0){m=11;y--}if(m>11){m=0;y++}state.month={y,m};state.selectedDate=null;renderCalendar()}
function bindCalendarControls(){$('prevMonth').onclick=()=>changeMonth(-1);$('nextMonth').onclick=()=>changeMonth(1);$('todayMonth').onclick=()=>{const p=tzParts();state.month={y:+p.year,m:+p.month-1};state.selectedDate=todayKey();renderCalendar()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.calendarFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCalendar()})}
async function fetchJson(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(`${url}: ${r.status}`);return r.json()}
async function refreshCore(){try{const [progress,academics,daily,calendar]=await Promise.all([fetchJson(API.progress),fetchJson(API.academics),fetchJson(API.daily),fetchJson(API.calendar)]);state.progress=progress;state.academics=academics;state.daily=daily;state.calendar=calendar;renderTaskProgress();renderDeadlineRadar();renderNext();renderDailyPanels();renderCalendar();$('syncText').textContent='live · '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('syncDot').style.background='#83dcb4'}catch(e){console.error(e);$('syncText').textContent='sync issue · retrying';$('syncDot').style.background='#e08a91'}}
async function refreshWeather(){try{const r=await fetch(WEATHER+'&t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('weather');state.weather=await r.json();renderWeather()}catch(e){console.error(e);$('weatherCond').textContent='Weather unavailable'}}
function init(){document.querySelectorAll('[data-notion]').forEach(a=>a.href=NOTION);updateClock();renderHeroProgress();bindCalendarControls();refreshCore();refreshWeather();setInterval(updateClock,1000);setInterval(()=>{renderHeroProgress();renderNext()},30000);setInterval(refreshCore,30000);setInterval(refreshWeather,15*60000)}
window.addEventListener('DOMContentLoaded',init);
