'use strict';
(()=>{
 const {$,esc,empty}=NOcean,store=NOceanData.tasks;
 let tasks=[],projects=[],view='today',limit=25,loading=false,revision=0,creating=false,toastTimer;
 const lingering=new Set(),lingerViews=new Map(),rowPositions=new Map(),removalTimers=new Map();
 const pending=new Set();
 const entry=new URLSearchParams(location.search);let applyEntry=true;
 const hints={today:'Planned work, rolled-over tasks, and unplanned urgent obligations.',tomorrow:'Your plan for tomorrow. Due dates are kept exactly as entered.',upcoming:'Days 2–14. Tomorrow has its own queue; farther dates belong in Later.',later:'Deferred work, undated backlog, and dates beyond tomorrow.',all:'All current tasks. Filters and completion status still apply.'};
 const projectFor=t=>projects.find(p=>TaskFilters.belongs(t,p));
 function toast(text,undo){const node=$('moduleToast');node.replaceChildren(document.createTextNode(text));if(undo){const b=document.createElement('button');b.textContent='Undo';b.onclick=()=>{node.hidden=true;undo();};node.append(b);}node.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.hidden=true,7000);}
 function render(){
  for(const b of document.querySelectorAll('[data-view]')){b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));}
  const maintenance=view==='maintenance';
  $('capture').closest('section').hidden=maintenance;
  $('moduleTasks').hidden=maintenance;$('moduleTasks').closest('section').querySelector('.module-fields').hidden=maintenance;
  $('deferredNotice').hidden=maintenance;$('taskStatus').hidden=maintenance;
  NOceanUpkeep.render(view);NOceanSignals.workloadOutline($('moduleTasks').closest('section'),tasks,view);
  $('viewHint').textContent=maintenance?'Recurring upkeep. Due occurrences appear automatically in Today.':hints[view];
  if(maintenance){$('moreTasks').hidden=true;return;}
  const text=$('search').value.trim().toLowerCase(),today=TaskPlanning.day();
  const filtered=tasks.filter(t=>(t.status!=='done'||$('showDone').checked||(lingering.has(t.id)&&lingerViews.get(t.id)===view))&&(TaskPlanning.matches(t,view)||(view==='later'&&TaskPlanning.matches(t,'upcoming')))&&TaskFilters.matches(t,{project:$('projectFilter').value,difficulty:$('difficultyFilter').value},projects)&&(!text||(t.name+' '+t.course+' '+t.project).toLowerCase().includes(text))).sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||(a.scheduledFor||a.due||'9999').localeCompare(b.scheduledFor||b.due||'9999'));
  for(const id of lingering)if(lingerViews.get(id)===view){const at=filtered.findIndex(t=>t.id===id);if(at>=0){const [task]=filtered.splice(at,1);filtered.splice(Math.min(rowPositions.get(id)??at,filtered.length),0,task);}}
  const deferred=tasks.filter(t=>t.status!=='done'&&TaskPlanning.dateKey(t.due)&&TaskPlanning.dateKey(t.due)<=today&&TaskPlanning.bucket(t)!=='today').length;
  $('deferredNotice').textContent=deferred?`${deferred} due/overdue task${deferred===1?' is':'s are'} planned outside Today. Review All if needed.`:'';
  $('taskStatus').textContent=`${filtered.length} task${filtered.length===1?'':'s'} · ${pending.size?'Saving…':'Synced with Home'}`;
  const shown=filtered.slice(0,limit),rowHTML=t=>{
   const busy=pending.has(t.id),done=t.status==='done',plan=TaskPlanning.label(t),source=NOcean.safeURL(t.sourceUrl),due=Deadlines.label(t.due);
   return `<article class="module-task ${done?'done':''}" data-task-id="${esc(t.id)}"><input type="checkbox" data-complete="${esc(t.id)}" ${done?'checked':''} ${busy?'disabled':''} aria-label="${done?'Reopen':'Complete'} ${esc(t.name)}"><div class="module-task-content"><button class="task-name" data-edit="${esc(t.id)}" ${busy?'disabled':''}>${NOceanIcons.slot(t,projectFor(t))}<span>${esc(t.name)}</span></button><div class="task-meta"><span>${esc(t.difficulty||'Unrated')}</span><span>${esc(t.course||t.project||'')}</span>${plan?`<span>${esc(plan)}</span>`:''}${due?`<span class="${TaskPlanning.dateKey(t.due)<today&&!done?'overdue':''}">Due ${esc(due)}</span>`:''}${source?`<a href="${esc(source)}" target="_blank" rel="noopener">Source ↗</a>`:''}</div><div class="module-actions" aria-label="Plan ${esc(t.name)}">${['today','tomorrow','later'].map(key=>`<button data-plan="${key}" data-task="${esc(t.id)}" ${busy?'disabled':''}>${key==='later'?'Backlog':key[0].toUpperCase()+key.slice(1)}</button>`).join('')}</div></div></article>`;
  },blank=empty('Nothing here. Add a task or adjust the filters.');
  if(typeof TaskMotion!=='undefined')TaskMotion.render($('moduleTasks'),shown,rowHTML,blank);else $('moduleTasks').innerHTML=shown.map(rowHTML).join('')||blank;
  $('moreTasks').hidden=filtered.length<=limit;
  NOceanUpkeep.render(view);
  if(typeof NOceanAppearance!=='undefined')NOceanAppearance.apply();
 }
 async function load(){if(loading||pending.size||creating)return;loading=true;const version=revision;$('refresh').disabled=true;try{const [a,b]=await Promise.all([store.list(),NOceanData.projects.list()]);if(version!==revision)return;tasks=a.tasks;projects=b.projects;for(const id of ['captureProject','editProject','projectFilter']){const select=$(id),old=select.value;select.innerHTML=`<option value="${id==='projectFilter'?'all':''}">${id==='projectFilter'?'All projects':'No project'}</option>`+projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');select.value=old|| (id==='projectFilter'?'all':'');}if(applyEntry){applyEntry=false;const project=projects.find(p=>p.id===entry.get('project'));if(project){$('projectFilter').value=project.id;$('captureProject').value=project.id;if(['today','tomorrow','upcoming','later','all'].includes(entry.get('view')))view=entry.get('view');const task=tasks.find(t=>t.id===entry.get('task')&&TaskFilters.belongs(t,project));if(task)edit(task.id);}}render();}catch(e){$('taskStatus').textContent=e.message+' Existing tasks remain visible.';}finally{loading=false;$('refresh').disabled=false;}}
 async function update(id,changes,allowUndo=true){if(pending.has(id))return false;const old=tasks.find(t=>t.id===id);if(!old)return false;$('moduleToast').hidden=true;clearTimeout(toastTimer);clearTimeout(removalTimers.get(id));removalTimers.delete(id);const completing=changes.status==='done'&&old.status!=='done',started=Date.now();if(completing){rowPositions.set(id,filteredPosition(id));lingerViews.set(id,view);lingering.add(id);}if(changes.status!=='done'){lingering.delete(id);lingerViews.delete(id);rowPositions.delete(id);}pending.add(id);revision++;tasks=tasks.map(t=>t.id===id?{...t,...changes}:t);render();try{const result=await store.update({id,...changes});tasks=tasks.map(t=>t.id===id?result.task:t);const undo=Object.fromEntries(Object.keys(changes).map(k=>[k,old[k]??null]));if(completing){removalTimers.set(id,setTimeout(()=>{lingering.delete(id);lingerViews.delete(id);rowPositions.delete(id);removalTimers.delete(id);render();},Math.max(0,3000-(Date.now()-started))));toast('Task completed.',allowUndo?()=>update(id,undo,false):null);}else toast(changes.planningMode?'Plan saved. Deadline unchanged.':'Task saved.',allowUndo?()=>update(id,undo,false):null);return true;}catch(e){lingering.delete(id);lingerViews.delete(id);rowPositions.delete(id);tasks=tasks.map(t=>t.id===id?old:t);$('editError').textContent=e.message;toast('Save failed. The task was restored.');return false;}finally{pending.delete(id);revision++;render();}}
 function filteredPosition(id){return [...$('moduleTasks').querySelectorAll('[data-task-id]')].findIndex(row=>row.dataset.taskId===id);}
 function edit(id){const t=tasks.find(t=>t.id===id);if(!t||pending.has(id))return;const d=Deadlines.fields(t.due);$('editId').value=id;$('editName').value=t.name;$('editDue').value=d.date;$('editTime').value=d.time;$('editDue').dataset.original=d.date;$('editTime').dataset.original=d.time;$('editDifficulty').value=t.difficulty||'Unrated';$('editProject').value=projectFor(t)?.id||'';$('editProject').dataset.original=$('editProject').value;$('editError').textContent='';$('taskEditor').showModal();}
 document.addEventListener('nocean:upkeep',()=>NOceanSignals.workloadOutline($('moduleTasks').closest('section'),tasks,view));
 $('capture').addEventListener('submit',async e=>{e.preventDefault();if(creating)return;creating=true;revision++;$('captureSave').disabled=true;const name=$('taskName').value.trim();try{const result=await store.create({name,difficulty:$('captureDifficulty').value,projectId:$('captureProject').value||null,due:Deadlines.serialize($('captureDue').value,$('captureTime').value),...TaskPlanning.change($('capturePlan').value)});tasks.unshift(result.task);view=$('capturePlan').value;limit=25;if($('taskName').value.trim()===name)$('taskName').value='';render();toast('Task added.');}catch(error){toast(error.message);}finally{creating=false;revision++;$('captureSave').disabled=false;}});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;limit=25;render();}if(b.dataset.plan)update(b.dataset.task,TaskPlanning.change(b.dataset.plan));if(b.dataset.edit)edit(b.dataset.edit);});
 $('moduleTasks').addEventListener('change',e=>{if(e.target.dataset.complete)update(e.target.dataset.complete,{status:e.target.checked?'done':'next'});});
 $('editForm').addEventListener('submit',async e=>{e.preventDefault();const changes={name:$('editName').value.trim(),difficulty:$('editDifficulty').value};if($('editProject').value!==$('editProject').dataset.original)changes.projectId=$('editProject').value||null;if($('editDue').value!==$('editDue').dataset.original||$('editTime').value!==$('editTime').dataset.original)changes.due=Deadlines.serialize($('editDue').value,$('editTime').value);$('saveEdit').disabled=true;if(await update($('editId').value,changes,false))$('taskEditor').close();$('saveEdit').disabled=false;});
 $('cancelEdit').onclick=()=>$('taskEditor').close();
 $('archiveTask').onclick=async()=>{const id=$('editId').value;if(pending.has(id))return;pending.add(id);revision++;$('archiveTask').disabled=true;try{await store.archive(id);tasks=tasks.filter(t=>t.id!==id);$('taskEditor').close();toast('Archived. Recoverable from Notion Trash.');}catch(e){$('editError').textContent=e.message;}finally{pending.delete(id);revision++;$('archiveTask').disabled=false;render();}};
 for(const id of ['projectFilter','difficultyFilter','showDone'])$(id).onchange=()=>{limit=25;render();};$('search').oninput=()=>{limit=25;render();};$('moreTasks').onclick=()=>{limit+=25;render();};$('refresh').onclick=load;
 window.addEventListener('focus',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(()=>{if(!document.hidden)load();},90000);let currentDay=TaskPlanning.day();setInterval(()=>{if(currentDay!==TaskPlanning.day()){currentDay=TaskPlanning.day();render();}},30000);load();
})();
