'use strict';
(()=>{
 const {$,esc,empty}=NOcean,store=NOceanData.tasks;
 let tasks=[],projects=[],courses=[],view='today',limit=25,loading=false,revision=0,creating=false,toastTimer,captureDrafts=[],editDrafts=[];
 const pending=new Set(),entry=new URLSearchParams(location.search);let applyEntry=true;
 const hints={today:'Planned work, rolled-over steps, and urgent deliverables.',tomorrow:'Work planned for tomorrow. Deadlines stay exactly as entered.',upcoming:'Work planned in the next 2–14 days.',later:'Unscheduled steps, backlog, and work beyond two weeks.',all:'All current manual tasks.'};
 const projectFor=t=>projects.find(p=>TaskFilters.belongs(t,p));
 const isMulti=t=>t.taskType==='Multi-step';
 const progress=t=>({done:(t.steps||[]).filter(s=>s.done).length,total:(t.steps||[]).length});
 function toast(text,undo){const node=$('moduleToast');node.replaceChildren(document.createTextNode(text));if(undo){const button=document.createElement('button');button.type='button';button.textContent='Undo';button.onclick=()=>{node.hidden=true;undo();};node.append(button);}node.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.hidden=true,6500);}
 function stepRows(t,all=false){const steps=all?(t.steps||[]):TaskPlanning.relevantSteps(t,view);return steps.map(s=>`<label class="task-step"><input type="checkbox" data-step-complete="${esc(s.id)}" data-task="${esc(t.id)}" ${s.done?'checked':''} ${pending.has(t.id)?'disabled':''}><span>${esc(s.name)}</span>${s.plannedFor?`<time datetime="${esc(s.plannedFor)}">${esc(s.plannedFor)}</time>`:'<time>Backlog</time>'}</label>`).join('');}
 function taskRow(t){
  const busy=pending.has(t.id),done=t.status==='done',plan=TaskPlanning.label(t),source=NOcean.safeURL(t.sourceUrl),due=Deadlines.label(t.due),p=progress(t),relevant=isMulti(t)?stepRows(t):'';
  const urgent=isMulti(t)&&!done&&TaskPlanning.dateKey(t.due)<=TaskPlanning.day()&&!TaskPlanning.relevantSteps(t,'today').length;
  return `<article class="module-task ${done?'done':''}" data-task-id="${esc(t.id)}">${isMulti(t)?`<span class="task-progress" aria-label="${p.done} of ${p.total} steps complete">${p.done}/${p.total}</span>`:`<input type="checkbox" data-complete="${esc(t.id)}" ${done?'checked':''} ${busy?'disabled':''} aria-label="${done?'Reopen':'Complete'} ${esc(t.name)}">`}<div class="module-task-content"><button class="task-name" data-edit="${esc(t.id)}" ${busy?'disabled':''}>${NOceanIcons.slot(t,projectFor(t))}<span>${esc(t.name)}</span></button><div class="task-meta"><span class="priority-chip priority-${esc((t.priority||'Normal').toLowerCase())}">${esc(t.priority||'Normal')}</span><span>${esc(t.taskType||'Simple')}</span><span>${esc(t.course||t.project||'')}</span>${!isMulti(t)&&plan?`<span>${esc(plan)}</span>`:''}${due?`<span class="${TaskPlanning.dateKey(t.due)<TaskPlanning.day()&&!done?'overdue':''}">Due ${esc(due)}</span>`:''}${source?`<a href="${esc(source)}" target="_blank" rel="noopener">Source ↗</a>`:''}</div>${urgent?'<p class="due-warning">Due now · no step planned today</p>':''}${isMulti(t)?`<div class="task-steps">${relevant||'<p class="section-note">No open steps in this view.</p>'}<details><summary>All steps</summary>${stepRows(t,true)||'<p class="section-note">Add the first step in Edit.</p>'}</details></div>`:`<div class="module-actions" aria-label="Plan ${esc(t.name)}">${['today','tomorrow','later'].map(key=>`<button data-plan="${key}" data-task="${esc(t.id)}" ${busy?'disabled':''}>${key==='later'?'Backlog':key[0].toUpperCase()+key.slice(1)}</button>`).join('')}</div>`}</div></article>`;
 }
 function render(){
  document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});$('viewHint').textContent=hints[view];
  const text=$('search').value.trim().toLowerCase(),type=$('typeFilter').value;
  const filtered=tasks.filter(t=>!String(t.sourceId||'').startsWith('brightspace:')&&(t.status!=='done'||$('showDone').checked)&&TaskPlanning.matches(t,view)&&(type==='all'||(t.taskType||'Simple')===type)&&TaskFilters.matches(t,{project:$('projectFilter').value,difficulty:'all'},projects)&&(!text||(t.name+' '+t.course+' '+t.project).toLowerCase().includes(text))).sort((a,b)=>Number(a.status==='done')-Number(b.status==='done')||(a.scheduledFor||a.due||'9999').localeCompare(b.scheduledFor||b.due||'9999'));
  $('deferredNotice').textContent='';$('taskStatus').textContent=`${filtered.length} task${filtered.length===1?'':'s'} · ${pending.size?'Saving…':'Synced with Home'}`;
  const shown=filtered.slice(0,limit),blank=empty('Nothing here. Add a task or adjust the filters.');$('moduleTasks').innerHTML=shown.map(taskRow).join('')||blank;$('moreTasks').hidden=filtered.length<=limit;if(typeof NOceanAppearance!=='undefined')NOceanAppearance.apply();
 }
 function populateSelects(){for(const id of ['captureProject','editProject','projectFilter']){const select=$(id),old=select.value;select.innerHTML=`<option value="${id==='projectFilter'?'all':''}">${id==='projectFilter'?'All projects':'No project'}</option>`+projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');select.value=old||(id==='projectFilter'?'all':'');}for(const id of ['captureCourse','editCourse']){const select=$(id),old=select.value;select.innerHTML='<option value="">None</option>'+courses.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');select.value=old;}}
 async function load(){if(loading||pending.size||creating)return;loading=true;const version=revision;$('refresh').disabled=true;try{const [a,b]=await Promise.all([store.list(),NOceanData.projects.list()]);if(version!==revision)return;tasks=a.tasks;courses=a.courses||[];projects=b.projects;populateSelects();if(applyEntry){applyEntry=false;const project=projects.find(p=>p.id===entry.get('project'));if(project){$('projectFilter').value=project.id;$('captureProject').value=project.id;view=['today','tomorrow','upcoming','later','all'].includes(entry.get('view'))?entry.get('view'):'all';const task=tasks.find(t=>t.id===entry.get('task')&&TaskFilters.belongs(t,project));if(task)edit(task.id);}}render();}catch(e){$('taskStatus').textContent=e.message+' Existing tasks remain visible.';}finally{loading=false;$('refresh').disabled=false;}}
 async function update(id,changes,allowUndo=true){if(pending.has(id))return false;const old=tasks.find(t=>t.id===id);if(!old)return false;pending.add(id);revision++;tasks=tasks.map(t=>t.id===id?{...t,...changes}:t);render();try{const result=await store.update({id,...changes});result.task.steps=old.steps||[];tasks=tasks.map(t=>t.id===id?result.task:t);const undo=Object.fromEntries(Object.keys(changes).map(key=>[key,old[key]??null]));toast(changes.status==='done'?'Task completed.':'Task saved.',allowUndo?()=>update(id,undo,false):null);return true;}catch(e){tasks=tasks.map(t=>t.id===id?old:t);$('editError').textContent=e.message;toast('Save failed. The task was restored.');return false;}finally{pending.delete(id);revision++;render();}}
 async function updateStep(taskId,step,changes){if(pending.has(taskId))return;pending.add(taskId);render();try{const result=await NOceanData.steps.update({taskId,...step,...changes});tasks=tasks.map(t=>t.id===taskId?{...t,status:result.parent.status,steps:t.steps.map(s=>s.id===step.id?result.step:s)}:t);toast(changes.done?'Step completed.':'Step saved.');}catch(e){toast(e.message);}finally{pending.delete(taskId);render();}}
 function draftRow(draft,index,mode){return `<div class="step-edit-row" data-step-index="${index}"><label>Step<input data-step-name value="${esc(draft.name||'')}" maxlength="300" required></label><label>Planned date<input data-step-date type="date" value="${esc(draft.plannedFor||'')}"></label><button type="button" data-remove-step="${index}">Remove</button></div>`;}
 function renderDrafts(mode){const drafts=mode==='capture'?captureDrafts:editDrafts,$list=$(mode+'StepList');$list.innerHTML=drafts.map((d,i)=>draftRow(d,i,mode)).join('');$list.querySelectorAll('[data-step-name]').forEach((n,i)=>n.oninput=()=>drafts[i].name=n.value);$list.querySelectorAll('[data-step-date]').forEach((n,i)=>n.oninput=()=>drafts[i].plannedFor=n.value||null);$list.querySelectorAll('[data-remove-step]').forEach(b=>b.onclick=async()=>{const d=drafts[Number(b.dataset.removeStep)];if(mode==='edit'&&d.id){try{await NOceanData.steps.remove({taskId:$('editId').value,id:d.id,editedAt:d.editedAt});}catch(e){$('editError').textContent=e.message;return;}}drafts.splice(Number(b.dataset.removeStep),1);renderDrafts(mode);});}
 function addDraft(mode){(mode==='capture'?captureDrafts:editDrafts).push({name:'',plannedFor:null,done:false});renderDrafts(mode);}
 function edit(id){const t=tasks.find(t=>t.id===id);if(!t||pending.has(id))return;const d=Deadlines.fields(t.due);$('editId').value=id;$('editName').value=t.name;$('editDue').value=d.date;$('editTime').value=d.time;$('editDue').dataset.original=d.date;$('editTime').dataset.original=d.time;$('editType').value=t.taskType||'Simple';$('editType').disabled=isMulti(t)&&(t.steps||[]).length>0;$('editPriority').value=t.priority||'Normal';$('editCourse').value=t.course||'';$('editProject').value=projectFor(t)?.id||'';$('editProject').dataset.original=$('editProject').value;$('editError').textContent='';editDrafts=(t.steps||[]).map(s=>({...s}));$('editSteps').hidden=!isMulti(t);renderDrafts('edit');$('taskEditor').showModal();}
 async function saveDrafts(taskId,drafts,existing=[]){for(const draft of drafts){if(!draft.name.trim())throw Error('Every step needs a name.');if(draft.id){const old=existing.find(s=>s.id===draft.id);if(!old||old.name!==draft.name.trim()||old.plannedFor!==(draft.plannedFor||null)){const result=await NOceanData.steps.update({taskId,...draft,name:draft.name.trim(),plannedFor:draft.plannedFor||null});draft.editedAt=result.step.editedAt;}}else{const result=await NOceanData.steps.create({taskId,requestId:crypto.randomUUID(),name:draft.name.trim(),plannedFor:draft.plannedFor||null,done:false});Object.assign(draft,result.step);}}return drafts;}
 $('captureType').onchange=()=>{$('captureSteps').hidden=$('captureType').value!=='Multi-step';$('capturePlan').disabled=$('captureType').value==='Multi-step';if($('captureType').value==='Multi-step'&&!captureDrafts.length)addDraft('capture');};$('addCaptureStep').onclick=()=>addDraft('capture');$('addEditStep').onclick=()=>addDraft('edit');$('editType').onchange=()=>{$('editSteps').hidden=$('editType').value!=='Multi-step';if($('editType').value==='Multi-step'&&!editDrafts.length)addDraft('edit');};
 $('capture').onsubmit=async e=>{e.preventDefault();if(creating)return;creating=true;revision++;$('captureSave').disabled=true;const name=$('taskName').value.trim(),taskType=$('captureType').value;try{const plan=taskType==='Simple'?TaskPlanning.change($('capturePlan').value):TaskPlanning.change('automatic'),result=await store.create({name,taskType,course:$('captureCourse').value,priority:$('capturePriority').value,projectId:$('captureProject').value||null,due:Deadlines.serialize($('captureDue').value,$('captureTime').value),...plan});result.task.steps=[];if(taskType==='Multi-step')result.task.steps=await saveDrafts(result.task.id,captureDrafts);tasks.unshift(result.task);view=taskType==='Multi-step'?'all':$('capturePlan').value;$('taskName').value='';captureDrafts=[];renderDrafts('capture');toast('Task added.');render();}catch(error){toast(error.message);}finally{creating=false;revision++;$('captureSave').disabled=false;}};
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;limit=25;render();}if(b.dataset.plan)update(b.dataset.task,TaskPlanning.change(b.dataset.plan));if(b.dataset.edit)edit(b.dataset.edit);});
 $('moduleTasks').onchange=e=>{if(e.target.dataset.complete)update(e.target.dataset.complete,{status:e.target.checked?'done':'next'});if(e.target.dataset.stepComplete){const t=tasks.find(x=>x.id===e.target.dataset.task),s=t?.steps.find(x=>x.id===e.target.dataset.stepComplete);if(s)updateStep(t.id,s,{done:e.target.checked});}};
 $('editForm').onsubmit=async e=>{e.preventDefault();const id=$('editId').value,t=tasks.find(x=>x.id===id),changes={name:$('editName').value.trim(),taskType:$('editType').value,course:$('editCourse').value,priority:$('editPriority').value};if($('editProject').value!==$('editProject').dataset.original)changes.projectId=$('editProject').value||null;if($('editDue').value!==$('editDue').dataset.original||$('editTime').value!==$('editTime').dataset.original)changes.due=Deadlines.serialize($('editDue').value,$('editTime').value);$('saveEdit').disabled=true;try{if(await update(id,changes)){if(changes.taskType==='Multi-step'){const steps=await saveDrafts(id,editDrafts,t.steps||[]);tasks=tasks.map(x=>x.id===id?{...x,steps}:x);}$('taskEditor').close();render();}}catch(error){$('editError').textContent=error.message;}finally{$('saveEdit').disabled=false;}};
 $('cancelEdit').onclick=()=>$('taskEditor').close();$('archiveTask').onclick=async()=>{const id=$('editId').value;try{await store.archive(id);tasks=tasks.filter(t=>t.id!==id);$('taskEditor').close();toast('Archived. Recoverable from Notion Trash.');render();}catch(e){$('editError').textContent=e.message;}};
 for(const id of ['projectFilter','typeFilter','showDone'])$(id).onchange=()=>{limit=25;render();};$('search').oninput=()=>{limit=25;render();};$('moreTasks').onclick=()=>{limit+=25;render();};$('refresh').onclick=load;window.addEventListener('focus',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});load();
})();
