const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const read=name=>fs.readFileSync(name,'utf8');
const pages={home:read('index.html'),projects:read('projects.html'),athletics:read('athletics.html'),settings:read('integrations.html')};
assert.match(read('nocean-ui.js'),/\['home','\/','Home'\],\['projects','\/projects\.html','Projects'\],\['athletics','\/athletics\.html','Athletics'\],\['settings','\/integrations\.html','Settings'\]/);
assert.doesNotMatch(read('nocean-ui.js'),/\['tasks'.*'Tasks'\]/);
for(const [name,html] of Object.entries(pages))assert.match(html,new RegExp(`data-page="${name}"`));
for(const text of ['Tasks','Deadlines','Events','Calendar'])assert.match(pages.home,new RegExp(text));
for(const id of ['academicRadar','taskList','eventList','calendarGrid'])assert.match(pages.home,new RegExp(`id="${id}"`));
assert.doesNotMatch(pages.home,/class="card projects-card"/);assert.match(read('home.js'),/NOceanStore\.isRadarItem/);assert.match(read('home.js'),/calendarItems/);
const projectSurface=pages.projects+read('projects.js')+read('project-plan.js');for(const text of ['project-ribbon','project-control-panel','Next','Structure and milestones'])assert.match(projectSurface,new RegExp(text));
assert.match(pages.athletics,/Athletics dashboard coming next/i);assert.match(pages.athletics,/\/machine\.html/);
for(const text of ['Nutrition','Sleep','Habits','Maintenance','Reflection / hotwash'])assert.match(read('machine.html'),new RegExp(text));
for(const text of ['Appearance and biomes','Current classes','Recurring maintenance','Integrations'])assert.match(pages.settings,new RegExp(text));
const memory=new Map(),context={localStorage:{getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)},crypto:{randomUUID:()=> '11111111-1111-4111-8111-111111111111'}};vm.createContext(context);vm.runInContext(read('nocean-store.js')+';globalThis.store=NOceanStore',context);
assert.equal(context.store.settings().classes.length,5);const task={id:'coursework',name:'Lab',due:'2026-09-23'};context.store.setVerification(task,'submitted');assert.equal(context.store.verification(task),'submitted');
context.store.completeMaintenance('sheets','2026-09-21');assert.equal(context.store.maintenanceStatus('2026-09-21').find(x=>x.id==='sheets').completedToday,true);
context.store.addReflection({date:'2026-09-21',type:'Hotwash',title:'Sprint',body:'Keep the good part.'});assert.equal(context.store.machine().reflections[0].title,'Sprint');
console.log('Sketch UI contracts passed: four destinations, Home hierarchy, Projects control panel, Athletics shell, preserved tracker, and Settings ownership.');
