const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const c=vm.createContext({document:{addEventListener(){}},fetch(){throw new Error('Cosmetics must not fetch application data');}});vm.runInContext(fs.readFileSync('nocean-appearance.js','utf8'),c);const run=s=>vm.runInContext(s,c);
assert.equal(run(`NOceanAppearance.validate({image:'https://elsewhere.invalid/x',tint:'unknown',visibility:'invisible'},'kelp-day').image`),'kelp-day');
assert.equal(run(`NOceanAppearance.validate({image:'none',tint:'Reef',visibility:'Strong'}).tint`),'Reef');
assert.equal(run(`Object.keys(NOceanAppearance.assets).length`),19);
console.log('Cosmetic asset allowlist and safe defaults passed.');
assert.equal(run(`NOceanAppearance.validate({rotatingMessages:false,message:'My reminder'}).message`),'My reminder');
assert.equal(run(`NOceanAppearance.validate({}).rotatingMessages`),true);
assert.equal(run(`NOceanAppearance.validate({message:'x'.repeat(500)}).message.length`),180);
for(const image of ['blood-kelp','grand-reef','kelp-day','kelp-night','twisty-bridge','twisty-bridge-night'])assert.equal(run(`NOceanAppearance.validate({image:'${image}'}).image`),image);
